extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  project: ./tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - simple-import-sort
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
